# ---
# "Named Things"
# ---
human gene:
  is_a: gene
  represented_as: node
  preferred_id: ensembl
  label_in_input: ensembl
  properties:
    approvedSymbol: str
    approvedName: str
    name: str
    biotype: str
    isInMembrane : double
    isSecreted : double
    hasSafetyEvent : double
    hasPocket : double
    hasLigand : double
    hasSmallMoleculeBinder : double
    geneticConstraint : double
    paralogMaxIdentityPercentage : double
    mouseOrthologMaxIdentityPercentage : double
    isCancerDriverGene : double
    hasTEP : double
    hasMouseKO : double
    hasHighQualityChemicalProbes : double
    maxClinicalTrialPhase : double
    tissueSpecificity : double
    tissueDistribution : double

# otar has no Bioregistry entry
disease:
  represented_as: node
  preferred_id: [mondo.disease, efo.disease, hp.disease, orphanet.disease, otar.disease, oba.disease, ncit.disease, doid.disease, obi.disease, ogms.disease, go.disease, mp.disease]
  label_in_input: [mondo.disease, efo.disease, hp.disease, orphanet.disease, otar.disease, oba.disease, ncit.disease, doid.disease, obi.disease, ogms.disease, go.disease, mp.disease]
  properties:
    code: str
    name: str
    description: str
    ontology: str

drug:
  represented_as: node
  preferred_id: chembl
  label_in_input: chembl
  properties:
    canonicalSmiles: str
    inchiKey: str
    drugType: str
    blackBoxWarning: boolean
    name: str
    yearOfFirstApproval: double
    maximumClinicalTrialPhase: double
    parentId: str
    hasBeenWithdrawn: boolean
    isApproved: boolean
    tradeNames: str[]
    synonyms: str[]
    crossReferences: str
    childChemblIds: str
    linkedDiseases: str
    linkedTargets: str
    description: str
    IndicationCountInDisease: int

human phenotype ontology:
  is_a: phenotypic feature
  represented_as: node
  preferred_id: ['bfo.hpo', 'chebi.hpo', 'cl.hpo', 'go.hpo', 'hp.hpo', 'hsapdv.hpo', 'mpath.hpo', 'nbo.hpo', 'ncbitaxon.hpo', 'obi.hpo', 'pato.hpo', 'pr.hpo', 'so.hpo', 'uberon.hpo', 'hgnc.hpo']
  label_in_input: ['bfo.hpo', 'chebi.hpo', 'cl.hpo', 'go.hpo', 'hp.hpo', 'hsapdv.hpo', 'mpath.hpo', 'nbo.hpo', 'ncbitaxon.hpo', 'obi.hpo', 'pato.hpo', 'pr.hpo', 'so.hpo', 'uberon.hpo', 'hgnc.hpo']
  properties:
    dbXRefs: str[]
    description: str
    name: str
    namespace: str[]
    obsolete_terms: str[]
    parents: str[]

association by overall:
  is_a: gene to disease association
  represented_as: edge
  input_label: abo
  prederred_id: associations_o
  properties:
    score: float
    evidenceCount: int


association by overall direct indirect:
  is_a: gene to disease association
  represented_as: edge
  input_label: abodid
  prederred_id: associations_abodid
  properties:
    score: float
    evidenceCount: int

association by data source:
  is_a: gene to disease association
  represented_as: edge
  preferred_id: associations_ds
  input_label: [
    animal_model.abds,
    affected_pathway.abds,
    genetic_association.abds,
    literature.abds,
    rna_expression.abds,
    somatic_mutation.abds,
    known_drug.abds
]
  properties:
    score: float
    evidenceCount: int
    datasourceId : str

association by data source direct indirect:
  is_a: gene to disease association
  represented_as: edge
  preferred_id: associations_dsdid
  use_id: false
  input_label: [
    animal_model.abdsdid,
    affected_pathway.abdsdid,
    genetic_association.abdsdid,
    literature.abdsdid,
    rna_expression.abdsdid,
    somatic_mutation.abdsdid,
    known_drug.abdsdid
]
  properties:
    score: float
    evidenceCount: int
    datasourceId : str

association by data type:
  is_a: gene to disease association
  represented_as: edge
  preferred_id: associations_dt
  use_id: false
  input_label: [
    animal_model.abdt,
    affected_pathway.abdt,
    genetic_association.abdt,
    literature.abdt,
    rna_expression.abdt,
    somatic_mutation.abdt,
    known_drug.abdt
]
  properties:
    score: float
    evidenceCount: int
    datasourceId : str


association by data type direct indirect:
  is_a: gene to disease association
  represented_as: edge
  preferred_id: associations_dtdid
  use_id: false
  input_label: [
    animal_model.abdtdid,
    affected_pathway.abdtdid,
    genetic_association.abdtdid,
    literature.abdtdid,
    rna_expression.abdtdid,
    somatic_mutation.abdtdid,
    known_drug.abdtdid
]
  properties:
    score: float
    evidenceCount: int
    datasourceId : str

gene pairwise molecular interations:
  is_a: gene to gene association
  represented_as: edge
  preferred_id: gene_interactions
  input_label: molecular_interactions
  properties:
    sourceDatabase: str
    intA: str
    intABiologicalRole: str
    intB: str
    intBBiologicalRole: str
    speciesA: str
    speciesB: str
    count: int
    scoring: float


drug mechanism of action:
  is_a: drug to gene association
  represented_as: edge
  preferred_id: drug_moa
  input_label: dmoa
  properties:
    actionType: str
    mechanismOfAction: str
    targetName: str
    targetType: str
    # references: str

drug indications:
  is_a: entity to disease association
  preferred_id: drug_indications
  input_label: indications
  represented_as: edge
  properties:
    approvedIndications: str[]
    indicationCount: long
    efoName: str
    references: str[]
    maxPhaseForIndication: float

disease to phenotype:
  is_a: disease to phenotypic feature association
  preferred_id: disease_phenotype
  input_label: disease_phenotype
  represented_as: edge
  properties:
    evidence: str[]